# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 17 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale due to no recent activity. Although stale posts are lower priority, they will not be removed.'
        stale-pr-message: 'This pull request has been marked as stale due to no recent activity. Although stale posts are lower priority, they will not be removed.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
